name: Build Android APK from ZIP

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Unzip project
        run: unzip -o "pokemon_text_adventure.zip" -d .
        # After this, the project lives at ./pokemon_text_adventure

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
      
      - name: Flutter pub get
        working-directory: pokemon_text_adventure
        run: flutter pub get

      - name: Build release APK (debug-keystore signed)
        working-directory: pokemon_text_adventure
        run: flutter build apk --release --no-shrink

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kanto-text-adventure-apk
          path: pokemon_text_adventure/build/app/outputs/flutter-apk/app-release.apk